services:
  agent:
    build:
      context: ./
      dockerfile: ./dockerfile
    container_name: agent
    depends_on:
      - mongo
    ports:
      - 4242:4242
    tty: true
    command: python -m deeppavlov_agent.run -ch http_client --cors
  harvesters_maintenance_skill:
    build:
      context: ./skills/harvesters_maintenance_skill/
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3002
    volumes: []
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rule_based_response_selector:
    build:
      context: ./selectors/rule_based_response_selector/
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3003
    volumes: []
version: "3.7"
